***SABD Analysis***

In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

In [8]:
df = pd.read_csv('../input/school/sabd.csv', index_col=0)
df.head()

,id_men,id_pers,id_depl,heuredep,mindep,heurearr,minarr,D12,motifor,NB_velo,VP_DISPO,duree,motifor1,deptime,arrtime,midtime,heuremid,nb_veh,cluster,rhour
1,101012,101012001,1.010120e+09,14,0,14,5,290.0,1,1,0,5,DOM,2024-02-01 14:00:00,2024-02-01 14:05:00,2024-02-01 14:02:30,14,1,3,0
2,101012,101012001,1.010120e+09,14,35,14,40,290.0,32,1,0,5,SHO,2024-02-01 14:35:00,2024-02-01 14:40:00,2024-02-01 14:37:30,14,1,3,0
3,101012,101012001,1.010120e+09,14,45,15,5,1159.0,1,1,0,20,DOM,2024-02-01 14:45:00,2024-02-01 15:05:00,2024-02-01 14:55:00,14,1,3,0
4,101012,101012001,1.010120e+09,15,10,15,30,1159.0,42,1,0,20,SHO,2024-02-01 15:10:00,2024-02-01 15:30:00,2024-02-01 15:20:00,15,1,3,0
5,101012,101012001,1.010120e+09,20,45,21,10,1449.0,1,1,0,25,DOM,2024-02-01 20:45:00,2024-02-01 21:10:00,2024-02-01 20:57:30,20,1,3,0

In [15]:
df = df.iloc[:,[7,-3,-8,-1]]

In [16]:
df = df.values

In [18]:
X = df[:,0:4]
Y = df[:,-1]